apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: 
    server: https://api.c-80fffd4.kyma.ondemand.com
users:
- name: default-user
  user:
    token: 
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: default
    user: default-user
current-context: default-context
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5akNDQWQ2Z0F3SUJBZ0lRQ3pTQVRXLzk5UGVKUFpuSzBtbDZIekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEl4TVRJeE5USXdNREEwTWxvWERUTXhNVEl4TlRJdwpNREEwTWxvd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBS2cyTUhCRi9VWWEwWlNHSVhMK3p0TWtzeEUyNUNnMkhVQ2g3VFRGR25zMDdnbzYKaHhienJ6c3F1bmpESHl3RmJJd215QisrODdzcDNWTlhWbnhWTGk1dTFJMHBUYkRvZ3lGSHJic0hESk5IMnhYcAo3Q2VYd1IwMUk4Tm12Y01VMTc2aFdIWUJ1bnBqaStFamlLYVUrRWZ3WDRuNi9DZ2M3dHE2d2NiTUxsUTgzVkpnClEyNTBmV21nWWV0ZzRCaDN6R3lCaFBEb1FNYTkvNHZqUXRpeVNYbUhZcFpwNjQxRnFVaGRkWGgwK1c3NXZuaVoKWDk2bnozRlhoZmJUNEtDaXJSS3RwbVVWWHVzNWRCeXlYWGI5VHdwYnYwUG9ydkUzamdqTWpLanBwMjh2cDhSVgpIMTJoemlSb1FZSkJtc0hQQU9LSi9KanRiL21TRGVScFo4NktxdUVDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvCkJBUURBZ0dtTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkdzdmtrTGdqczZOREtkWGcxcEEKK29jRWJvV3BNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJWODBlVVBQcm1NZWFIVG0xQVphcU9HTTg4cStaZApiYUhWaHJpTzZET1dVV0tRZmxna1ovcFliODd4K2VxMXVPOWgvdXl4QzFYNlNwZjNlVENlV3NSRHRKdFpZVi9mCmU5ZkpGN2N1MmFrUFhvOHpYMHpZMWlhV1hCWHkrY01lVHNaNnZLZFZhYmdxb1N4SHlSMGp4TmtyM01KdGpyamIKWlhadHdhOHEwQ0E2NHJuZEppeFN3czJzZWpqNGRVaHFrU0h3V2g5UFNFTllncmY0cXlQNFlmOE83djZJUXI0UwpkSVdGZEZnYUUwb1NVdzVyMkJwS2pkR3RvT0VSYXdOZGUwY3puWDZIMHFkV3pBMC9OVG00LzN2QmxvZ2hxeU5pCjJJRE5vcmZsNjZBbDl4RWtPV2pWWk9BSWsrYlZQTUdVb3ZvaEhsS2VtVEhueEdaRVBvaUVCVkZsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://api.c-80fffd4.kyma.ondemand.com
users:
- name: default-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkgwWTluRktvOXAycVVRRTJ0X1RrZERNMENyZjBvUFRLM1B1Y1o4NFV1REEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiazgtc2VydmljZS1hY2NvdW50LXRva2VuLXF0eDR6Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Ims4LXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjYyMWRkNTY3LTIwYTUtNDZkYS05MjYxLTdjYTcwYjVhNGVkYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjYXA6azgtc2VydmljZS1hY2NvdW50In0.NH1nQ-2O6I4LW5UNu117RSF3UdP00srL1N8bvOybfWdUIsghP-NbHaNQltc6PLnPv5XCKSPZuzI4WKriW_F7gHHZceYj-xpep5JDOshF8p3ZvjTx4ZWpimAKtUT3fYqImVVVQnUDKtwJM0vBlJRKvZ-D_uwGy42JbqXMQFR406GPywHV30gp8aUpgAaJWtvM0kPuHGVQq1XC0JFZyN8TGLuMMk7ubJlkspZuMf3NgXFG-xnZcF9jJ4qM-cMF6VtWMKyVVpB18mAPgpHBZP9MYb8YvnPltBvjLVXFGPxWExnBPEOkCcwJh31U34SKWxnZdG7OR-3_8k6L44l0-MC5EJYTXspB_W_SFPmxB_Xkx0agFHkD1eci6on299M8u4RsBDzqVAHKNs0vldeCidrzV7bXCA8sbav6uCGC5mhlzhBMvmfJFyY1ggklA-NYIVwJx-Mvemmnd8GDgkpmmVWLg1JDfKfVgMSkIMw2LTmdYq2f9y867CC_gikPsW-eGlYuaCSKZCN3yiqxKNANIXPY1_m68wani4rITgYmBXbhBgzD6ZNgIyA-98XNrinD95J0UiZ20_rY9SbfFuYfmvpRVjM52aC0jALoKus4Knssr-k7lf8mlew2rT1C3_O3AfqeNw1gjRqgVa2PuaR0WVAtnLHov6bRMN-qNom_aoAd8YM
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: default
    user: default-user
current-context: default-context
apiVersion: v1
kind: Config
clusters:
- name: default-cluster
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5akNDQWQ2Z0F3SUJBZ0lRQ3pTQVRXLzk5UGVKUFpuSzBtbDZIekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1CNFhEVEl4TVRJeE5USXdNREEwTWxvWERUTXhNVEl4TlRJdwpNREEwTWxvd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBS2cyTUhCRi9VWWEwWlNHSVhMK3p0TWtzeEUyNUNnMkhVQ2g3VFRGR25zMDdnbzYKaHhienJ6c3F1bmpESHl3RmJJd215QisrODdzcDNWTlhWbnhWTGk1dTFJMHBUYkRvZ3lGSHJic0hESk5IMnhYcAo3Q2VYd1IwMUk4Tm12Y01VMTc2aFdIWUJ1bnBqaStFamlLYVUrRWZ3WDRuNi9DZ2M3dHE2d2NiTUxsUTgzVkpnClEyNTBmV21nWWV0ZzRCaDN6R3lCaFBEb1FNYTkvNHZqUXRpeVNYbUhZcFpwNjQxRnFVaGRkWGgwK1c3NXZuaVoKWDk2bnozRlhoZmJUNEtDaXJSS3RwbVVWWHVzNWRCeXlYWGI5VHdwYnYwUG9ydkUzamdqTWpLanBwMjh2cDhSVgpIMTJoemlSb1FZSkJtc0hQQU9LSi9KanRiL21TRGVScFo4NktxdUVDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvCkJBUURBZ0dtTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRkdzdmtrTGdqczZOREtkWGcxcEEKK29jRWJvV3BNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJWODBlVVBQcm1NZWFIVG0xQVphcU9HTTg4cStaZApiYUhWaHJpTzZET1dVV0tRZmxna1ovcFliODd4K2VxMXVPOWgvdXl4QzFYNlNwZjNlVENlV3NSRHRKdFpZVi9mCmU5ZkpGN2N1MmFrUFhvOHpYMHpZMWlhV1hCWHkrY01lVHNaNnZLZFZhYmdxb1N4SHlSMGp4TmtyM01KdGpyamIKWlhadHdhOHEwQ0E2NHJuZEppeFN3czJzZWpqNGRVaHFrU0h3V2g5UFNFTllncmY0cXlQNFlmOE83djZJUXI0UwpkSVdGZEZnYUUwb1NVdzVyMkJwS2pkR3RvT0VSYXdOZGUwY3puWDZIMHFkV3pBMC9OVG00LzN2QmxvZ2hxeU5pCjJJRE5vcmZsNjZBbDl4RWtPV2pWWk9BSWsrYlZQTUdVb3ZvaEhsS2VtVEhueEdaRVBvaUVCVkZsCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://api.c-80fffd4.kyma.ondemand.com
users:
- name: default-user
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkgwWTluRktvOXAycVVRRTJ0X1RrZERNMENyZjBvUFRLM1B1Y1o4NFV1REEifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXAiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoiazgtc2VydmljZS1hY2NvdW50LXRva2VuLXF0eDR6Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6Ims4LXNlcnZpY2UtYWNjb3VudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjYyMWRkNTY3LTIwYTUtNDZkYS05MjYxLTdjYTcwYjVhNGVkYyIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpjYXA6azgtc2VydmljZS1hY2NvdW50In0.NH1nQ-2O6I4LW5UNu117RSF3UdP00srL1N8bvOybfWdUIsghP-NbHaNQltc6PLnPv5XCKSPZuzI4WKriW_F7gHHZceYj-xpep5JDOshF8p3ZvjTx4ZWpimAKtUT3fYqImVVVQnUDKtwJM0vBlJRKvZ-D_uwGy42JbqXMQFR406GPywHV30gp8aUpgAaJWtvM0kPuHGVQq1XC0JFZyN8TGLuMMk7ubJlkspZuMf3NgXFG-xnZcF9jJ4qM-cMF6VtWMKyVVpB18mAPgpHBZP9MYb8YvnPltBvjLVXFGPxWExnBPEOkCcwJh31U34SKWxnZdG7OR-3_8k6L44l0-MC5EJYTXspB_W_SFPmxB_Xkx0agFHkD1eci6on299M8u4RsBDzqVAHKNs0vldeCidrzV7bXCA8sbav6uCGC5mhlzhBMvmfJFyY1ggklA-NYIVwJx-Mvemmnd8GDgkpmmVWLg1JDfKfVgMSkIMw2LTmdYq2f9y867CC_gikPsW-eGlYuaCSKZCN3yiqxKNANIXPY1_m68wani4rITgYmBXbhBgzD6ZNgIyA-98XNrinD95J0UiZ20_rY9SbfFuYfmvpRVjM52aC0jALoKus4Knssr-k7lf8mlew2rT1C3_O3AfqeNw1gjRqgVa2PuaR0WVAtnLHov6bRMN-qNom_aoAd8YM
contexts:
- name: default-context
  context:
    cluster: default-cluster
    namespace: default
    user: default-user
current-context: default-context
